all:
  hosts:
    localhost:
      ansible_connection: local
    ubun20-01:
      ansible_host: 172.17.29.61
      ansible_user: jwson
      ip: 172.17.29.61
      access_ip: 172.17.29.61
      ansible_become: true
      ansible_become_pass: <pw>
    ubun20-02:
      ansible_host: 172.17.29.62
      ansible_user: jwson
      ip: 172.17.29.62
      access_ip: 172.17.29.62
      ansible_become: true
      ansible_become_pass:  <pw>
    ubun20-03:
      ansible_host: 172.17.29.63
      ansible_user: jwson
      ip: 172.17.29.63
      access_ip: 172.17.29.63
      ansible_become: true
      ansible_become_pass:  <pw>
  children:
    kube_control_plane:
      hosts:
        ubun20-01:
        ubun20-02:
        ubun20-03:
    kube_node:
      hosts:
        ubun20-01:
        ubun20-02:
        ubun20-03:
    etcd:
      hosts:
        ubun20-01:
          ansible_host: 172.17.29.61
        ubun20-02:
          ansible_host: 172.17.29.62
        ubun20-03:
          ansible_host: 172.17.29.63
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
        calico_rr:
    calico_rr:
      hosts: {}

